### ISSUE TITLE
Add Quantum reference to Mitiq paper once published

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/unitary-fund#246]
Add Quantum reference of published paper once the Mitiq paper is published
Find all places where this should be added (research page, mitiq page, news?, etc.)

**Comment by natestemen** [comment]
https://quantum-journal.org/papers/q-2022-08-11-774/

**Comment by natestemen** [comment]
Assigning myself since Andrea is off for the next two weeks.
