### ISSUE TITLE
Add link for high school students resources 

### ISSUE THREAD

**Issue by BrianIngmanson** [unitaryfund/unitary-fund#27]
Link - https://quantumready.thinkific.com/

Description - This course will introduce the essential concepts used in quantum computing and explain how it's different than regular computing. We will explore what quantum computers can (and can't) do right now, and guide you through running first code on a real quantum computer. This is a **beginner** level course, so no linear algebra or tough equations will be used. That being said, you will NOT have enough background to go get a job after this course! You'll be able to understand what quantum computing is, and know where to go if you want to learn more.

Reason - You have a lot of great resources for students that have the math background. This course is more for people asking "wait, what even *is* quantum computing?" to explain what it is and why it matters

**Comment by nathanshammah** [comment]
Hi @BrianIngmanson, this is a great link, I didn't find it in @Lucaman99 blog post. Why was this issue closed? It looks like a great addition. Could you re-open the issue and open a PR for the webpage?

**Comment by BrianIngmanson** [comment]
Hey Nate,
 
Sorry! I thought I was doing the wrong thing. I kinda... suck... at Github.
 
I'll open it back up and navigate the pull request! Thanks so much.
 
-Brian
 
----- Original message -----From: Nathan Shammah <notifications@github.com>To: unitaryfund/unitary-fund <unitary-fund@noreply.github.com>Cc: Brian Ingmanson <brian.i@ibm.com>, Mention <mention@noreply.github.com>Subject: [EXTERNAL] Re: [unitaryfund/unitary-fund] Add link for high school students resources (#27)Date: Wed, Jul 22, 2020 1:14 PM 
 
Hi @BrianIngmanson, this is a great link, I didn't find it in @Lucaman99 blog post. Why was this issue closed? It looks like a great addition. Could you re-open the issue and open a PR for the webpage?

**Comment by Lucaman99** [comment]
Thanks @BrianIngmanson, this looks like a great resource!
