### ISSUE TITLE
New favicon

### ISSUE THREAD

**Issue by natestemen** [unitaryfund/unitary-fund#303]
The current favicon could use a refresher.

<img width="70" alt="Screenshot 2023-03-03 at 6 02 48 PM" src="https://user-images.githubusercontent.com/12703123/222869945-e5f06069-e444-4628-bd9d-0a4ac6ea2447.png">

@francespoblete is there a more recent one that I could swap in? I could have sworn we had a "UF" somewhere that maybe I can convert into an `ico`. No need to create one, especially since I know you have a lot on your plate right now, but if there is something out there (either an `ico`, or a file I can convert into one), feel free to drop a link and I'll take care of the rest.

**Comment by francespoblete** [comment]
@natestemen yes, we actually do. I thought we had this updated already. I haven't noticed that it's still the old favicon. Here are 2 choices. Feel free to use whichever :) 

![Favicon v1](https://user-images.githubusercontent.com/65167390/222980921-d326ea14-ee66-44d8-ae74-7184a2f9e1bc.png)
![Favicon v2](https://user-images.githubusercontent.com/65167390/222980924-4610134b-1554-40cc-98cf-2ec7a7d05b04.png)

**Comment by natestemen** [comment]
All set, I went with the square one. Thank you Frances!

For reference it looks like we used https://favicon.io/favicon-converter/ previously to convert the PNG to the necessary favicons. I used that again.

**Comment by natestemen** [comment]
@francespoblete actually do we have svg versions of the above? I'm reading https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs and it suggests having an SVG and letting the browser do some of the rescaling.
