### ISSUE TITLE
Sometimes text overlaps with top-right menu on mobile phone.

### ISSUE THREAD

**Issue by andreamari** [unitaryfund/unitary-fund#34]
With a narrow screen, the text "because evolution is unitary" overlaps with the top-right menu symbol (hamburger).
Android version: 9
Browser: Chrome

**Comment by willzeng** [comment]
Fixed by repositioning the tagline in https://github.com/unitaryfund/unitary-fund/commit/555bc76ce7367a9aa80e62454873142571af515d
