### ISSUE TITLE
Add page on publications

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/unitary-fund#39]
It could be divided into: 
- publications on microgrant projects by awardees. These are already referenced, sparse in the [Grants](https://unitary.fund/grants.html) page.  
- publications by Unitary Labs on Mitiq. 

Additionally, it could include:
- publications by Unitary Labs tech staff members.
- publications citing or using Mitiq (If there is a way to embed bibliometrics automatically, a plus. E.g., Google scholar rectangle, automatically updated).

**Comment by willzeng** [comment]
Do we still want to add the microgrant research? It's an empty section now?

**Comment by crazy4pi314** [comment]
I wasn't really ready to merge that PR so I have added #127 to address the grantee research
