### ISSUE TITLE
Update Talks page and add video links

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/unitary-fund#61]
Update the Talks page to put the latest one held from "upcoming" to "past", https://unitary.fund/talks.html, and add video links to the previous ones. It could include embedded html preview of the "Quantum Software Talks" collection from YouTube.
https://support.google.com/youtube/answer/171780?hl=en, https://www.youtube.com/watch?v=yxyqJDC4SUo&list=PL-VMs2BCTI_nnSQmBaccJ1CdQfw5cpHSp.

**Comment by willzeng** [comment]
@crazy4pi314 I think this is now updated yes? Should we close this issue?

**Comment by crazy4pi314** [comment]
Yup this is all done, including the video embeds as @nathanshammah  suggested.

**Comment by nathanshammah** [comment]
thanks @crazy4pi314.
