### ISSUE TITLE
Add list of Unitary Fund team papers

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/unitary-fund#89]
Add list of papers from Unitary Fund team members. The papers from the projects are scattered in the grants section, but maybe also those could be collected.

**Comment by willzeng** [comment]
Adding to the list here:

https://arxiv.org/abs/2005.10921

https://arxiv.org/abs/2009.04417

https://arxiv.org/abs/2104.15044

**Comment by nathanshammah** [comment]
https://arxiv.org/abs/2105.09902

https://arxiv.org/abs/2108.02237

Could also include a subsection for collaborations where UF staff members are involved, such as https://arxiv.org/abs/2101.05710, https://arxiv.org/abs/2104.09811.

This page could point to the https://github.com/unitaryfund/research repository and to the code-blocks in https://mitiq.readthedocs.io/en/latest/examples/mitiq-paper/mitiq-paper-codeblocks.html.

**Comment by crazy4pi314** [comment]
I think the solution to this could also resolve #39?  I'll take a stab at today

**Comment by crazy4pi314** [comment]
#115 resolves this I think, reopen if needed
